CREATE EXTENSION IF NOT EXISTS pgcrypto;

DROP TABLE IF EXISTS accounts CASCADE;
CREATE TABLE accounts (
    id SERIAL NOT NULL PRIMARY KEY,
    username VARCHAR(16) NOT NULL UNIQUE,
    password VARCHAR(128) NOT NULL,
    salt VARCHAR(64) NULL DEFAULT NULL,
    email VARCHAR(128) NOT NULL,
    email_code VARCHAR(256) NULL DEFAULT NULL,
    banned BOOLEAN NOT NULL DEFAULT FALSE,
    admin BOOLEAN NOT NULL DEFAULT FALSE,
    logged_in BOOLEAN NOT NULL DEFAULT FALSE,
    created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP WITH TIME ZONE NULL DEFAULT NULL,
    last_known_ip VARCHAR(32) NULL DEFAULT NULL
);

DROP TABLE IF EXISTS characters CASCADE;
CREATE TABLE characters (
    id SERIAL NOT NULL PRIMARY KEY,
    account_id INT NOT NULL REFERENCES accounts(id),
    name VARCHAR(16) NOT NULL DEFAULT '',
    level SMALLINT NOT NULL DEFAULT 0,
    attribute_points SMALLINT NOT NULL DEFAULT 0,
    last_use TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT '1970-01-01 00:00:00',
    created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS inventory_equipment;
CREATE TABLE inventory_equipment (
    id SERIAL NOT NULL PRIMARY KEY,
    character_id INT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    item_id INT NOT NULL DEFAULT 0,
    attack INT NOT NULL DEFAULT 0,
    magic INT NOT NULL DEFAULT 0,
    armor INT NOT NULL DEFAULT 0,
    position SMALLINT
);

DROP TABLE IF EXISTS ip_log;
CREATE TABLE ip_log (
    id SERIAL NOT NULL PRIMARY KEY,
    account_id INT NOT NULL REFERENCES accounts(id),
    ip VARCHAR(32) NOT NULL,
    authenticated BOOLEAN NOT NULL,
    ts TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS ban_log;
CREATE TABLE ban_log (
    id SERIAL NOT NULL PRIMARY KEY,
    account_id INT NOT NULL REFERENCES accounts(id),
    banned_by VARCHAR(64) NOT NULL,
    ban_reason TEXT NOT NULL,
    status SMALLINT NOT NULL DEFAULT 0,
    ts TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS user_specs_log;
CREATE TABLE user_specs_log (
    id SERIAL NOT NULL PRIMARY KEY,
    account_id INT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    browser VARCHAR(64) NOT NULL,
    os VARCHAR(64) NOT NULL,
    isp VARCHAR(64) NOT NULL,
    js_enabled BOOLEAN NOT NULL DEFAULT TRUE
);

DROP TABLE IF EXISTS cheat_log;
CREATE TABLE cheat_log (
    id SERIAL NOT NULL PRIMARY KEY,
    character_id INT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    offense VARCHAR(64) NOT NULL DEFAULT '',
    ts TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);